### ISSUE TITLE
Radiation detector

### ISSUE THREAD

**Issue by RoboSquid** [andrewgodwin/thestandard#27]
Radiacode 102 is very popular here.

**Comment by andrewgodwin** [comment]
I already presumed this one with https://github.com/andrewgodwin/thestandard/blob/main/_posts/2024-06-23-radiation-detector.md :)

Once I have figured out what a full page format looks like I'll flesh the rest of it out.

**Comment by RoboSquid** [comment]
Ahh thought everything was in issues... apologies.
